server:
  port: 9090

#dataSource可以使用druid
spring:
    datasource:
        name: dataSource
        url: jdbc:oracle:thin:@localhost:1521:XE
        username: orcl
        password: orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver



mybatis:
  mapper-locations: classpath:mybatis/mapper/sys/*.xml
  config-location: classpath:mybatis-config.xml